services:
  config-user00:
    build:
      context: ./sc/config
      dockerfile: ../../buildfile/Dockerfile_java
      args:
        - BUILD_LIB_DIR=build/libs
        - ARTIFACTORY_FILE=config.jar
    image: docker.io/${IMAGE_ORG}/config:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "9001"
    environment:
      SERVER_PORT: 9001
      GIT_URL: ${GIT_URL}
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_TOKEN: ${GIT_TOKEN}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - subride-user00
      
  eureka1-user00:  
    build:
      context: ./sc/eureka
      dockerfile: ../../buildfile/Dockerfile_java
      args:
        - BUILD_LIB_DIR=build/libs
        - ARTIFACTORY_FILE=eureka.jar
    image: docker.io/${IMAGE_ORG}/eureka:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "8761"
    environment:
      HOSTNAME: eureka1-user00
      SERVER_PORT: "8761"
      REGISTER_WITH_EUREKA: "true"
      FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka2-user00:8762/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - subride-user00
  eureka2-user00:  
    depends_on:
      eureka1-user00:
        condition: service_healthy  
    image: docker.io/${IMAGE_ORG}/eureka:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "8762"
    environment:
      HOSTNAME: eureka2-user00
      SERVER_PORT: "8762"
      REGISTER_WITH_EUREKA: "true"
      FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka1-user00:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - subride-user00 
  scg-user00:
    depends_on:
      eureka1-user00:
        condition: service_healthy
      eureka2-user00:
        condition: service_healthy
    build:
      context: ./sc/scg
      dockerfile: ../../buildfile/Dockerfile_java
      args:
        - BUILD_LIB_DIR=build/libs
        - ARTIFACTORY_FILE=scg.jar
    image: docker.io/${IMAGE_ORG}/scg:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "${SCG_PORT}:19080"
    environment:
      HOSTNAME: scg-user00
      SERVER_PORT: 19080
      EUREKA_SERVERS: ${EUREKA_SERVERS}
      ALLOWED_ORIGINS: ${FRONT_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - subride-user00    

  mysql-user00:
    image: mysql:8.0
    restart: "no"
    container_name: mysql-user00
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306" 
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - subride-user00  

  subrecommend-user00:
    depends_on:
      mysql-user00:
        condition: service_healthy
      eureka1-user00:
        condition: service_healthy
      eureka2-user00:
        condition: service_healthy
      config-user00:
        condition: service_healthy
    build:
      context: ./subrecommend/subrecommend-infra
      dockerfile: ../../buildfile/Dockerfile_java
      args:
        - BUILD_LIB_DIR=build/libs
        - ARTIFACTORY_FILE=subrecommend.jar
    image: docker.io/${IMAGE_ORG}/subrecommend:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "18081"
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: subrecommend-service
      HOSTNAME: subrecommend-user00
      SERVER_PORT: 18081
      EUREKA_SERVERS: ${EUREKA_SERVERS}
      DB_URL: "jdbc:mysql://mysql-user00:3306/subrecommend?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul"
    networks:
      - subride-user00

  subride-front-user00:
    build:
      context: .
      dockerfile: buildfile/Dockerfile_react_express
      args:
        - PROJECT_FOLDER=subride-front
        - BUILD_FOLDER=buildfile
        - EXPORT_PORT=3000
        - REACT_APP_API_BASE_URL=${SCG_HOST}    
    image: docker.io/${IMAGE_ORG}/subride-front:${IMAGE_VERSION}
    restart: "no"
    ports:
      - "${FRONT_PORT}:3000"
networks:
  subride-user00:
    driver: bridge

